version: '3.8'

services:
  neosale-crm:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: neosale-crm-app
    networks:
      - neosale-network

networks:
  neosale-network:
    driver: bridge