version: '3.8'

services:
  neosale-crm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://evolution-api-neosale-api.mrzt3w.easypanel.host/
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    container_name: neosale-crm-app
    networks:
      - neosale-network

networks:
  neosale-network:
    driver: bridge